Adds Non-Eutactic Blades and Variations
outer-haven/outer-haven pull request #204
Opened 2017-12-12 10:16 UTC by Michiyamenotehifunana

:cl: Toriate
add: Added the non-eutactic blade, fancy recolorable esword
add: Added the hyper-eutactic blade, supermassive recolorable desword
soundadd: added NEB sounds
imageadd: added NEB icons
/:cl:

![dreamseeker_2017-10-24_18-37-20](https://user-images.githubusercontent.com/31995558/33878740-38a5bcc6-df67-11e7-8823-fab2427bec15.png)

Non-Eutactic Blades (NEBs) are essentially, eswords except cool and fancy. It also rips off a different sci-fi universe. Their stats are different from regular eswords. They are also not implemented in any way whatsoever. The toy variants however, are craftable in-game with plastic, cable coils, and light tubes.

![dreamseeker_2017-10-24_18-31-21](https://user-images.githubusercontent.com/31995558/33878825-85ee043e-df67-11e7-9e74-22ecc1eea6e7.png)

![dreamseeker_2017-10-29_23-14-07](https://user-images.githubusercontent.com/31995558/33878866-9e3e06ec-df67-11e7-93ad-542ee1dc11d1.png)

Also included are Hyper-Eutactic Blades, a two handed variant similiar to the dual esword.

![dreamseeker_2017-12-01_20-25-49](https://user-images.githubusercontent.com/31995558/33878903-b9e35b86-df67-11e7-9a09-a7b80dd03618.png)

The actual stats are excessively overpowered and untested.

![dreamseeker_2017-12-02_00-01-06](https://user-images.githubusercontent.com/31995558/33878939-dce93e48-df67-11e7-9fbf-c5199f98cb17.png)

As none of the real variants are actually obtainable normally, they would have to be bussed in for testing in prod.

DISCLAIMER: None of the things shown in the screenshots aside from the swords are actually added in this PR. So no cool glowy knight armors are included.

2017-12-14 19:26 UTC, Kevak requested changes

2017-12-14 19:26 UTC, Kevak commented on haven/code/game/objects/items/melee/eutactic_blades.dm
> +		return 1
Remember the Boolians. This should be TRUE if it isn't intended to be a var.

2017-12-14 19:26 UTC, Kevak commented on haven/code/game/objects/items/melee/eutactic_blades.dm
> +		return 1
So yah. Just. Go through and find all the boolians.

2017-12-15 04:40 UTC, Michiyamenotehifunana commented
@Kevak should be fixed now

2017-12-15 06:16 UTC, Kevak approved these changes

2017-12-15 06:17 UTC, Kevak commented
Looks good but I'm gonna wait on sorting out the conflict that's causing problems with Travis. P sure we merged something derpy.

2017-12-16 14:09 UTC, nichlas0010 commented
Update your branch with the master to fix the conflicts

2017-12-19 23:00 UTC, Partheo commented
### Just finished testing this. Here are my thoughts and comments:

I love the amount of detail you've put into this PR. Small things like the impale on clumsiness, or the plastic craftable swords, and the hulk messages make this feel like a complete feature.

The sounds are loud, but so are the e-sword ones so I have no problem with that.

The hyper sword is hilarious. Way too much damage, so I'm glad this is staying as an admin-only item. We can try to find a good use for it eventually. Maybe some crazy lavaland loot? The sword definitely feels like a "final boss" drop item.

A recent PR changed how disability procs worked, so I updated the clumsiness check for you.

I feel like the message asking "Are you sure you want to change [the sword's] color?" is unecessary. You can just click cancel on the color selection dialogue. 

The hyper sword sprite was not centered, so I moved it cause it bugged me. Was that on purpose?

The sword attack animation only displays the hilt (off mode) icon when you hit something with it, unlike the e-sword. See this gif for more info:
![2017-12-19_16-54-03](https://user-images.githubusercontent.com/10659549/34182231-677c54fc-e4e3-11e7-9a73-f7f25abb1abd.gif)

#### Overall, pretty happy with this PR. Feels like a quality feature even though it's not used in game.

2017-12-19 23:01 UTC, merged