Adds Polychromic Clothes
outer-haven/outer-haven pull request #59
Opened 2017-12-03 05:16 UTC by Michiyamenotehifunana

:cl: Toriate
add: Added Polychromic clothes
tweak: Made mixed wardrobes spawn polychromic clothes
imageadd: added greyscaled sprites for polychromic clothes
/:cl:

![dreamseeker_2017-11-19_22-53-16](https://user-images.githubusercontent.com/31995558/33522615-cee31f00-d82b-11e7-903a-3bef7a25347a.png)

Polychromic clothes are recolourable by alt clicking them. They can have up to 3 recolourable overlays, and have a base sprite containing unrecolourable elements.

This PR introduces a framework for polychromic clothes, anyone can make one by providing up to 4 sprites: A base one, and up to 3 recolorable overlays for it, and then copypasting some code. This PR includes 5 example clothes, all spawning in mixed wardrobes.

2017-12-03 05:27 UTC, Kevak commented
Looks like we need to get the tagging system working properly. Darnit.

I'll add WIP. Ping me when its ready. I know yer fiddling with it.

2017-12-03 05:28 UTC, Kevak commented
Once I figure out how to add tags.

2017-12-03 06:02 UTC, Michiyamenotehifunana commented
Technically it's actually ready for merging, but I might as well polish it up. I just need to do list shenanigans that only affects the framework and not any of the example clothes added.

2017-12-03 06:10 UTC, Kevak commented
Alrighty. Ping when yer ready for review.

2017-12-03 11:15 UTC, Michiyamenotehifunana commented
@Kevak beep boop meow meow

2017-12-03 15:11 UTC, ActualRory commented
How many times can you change the colour of the clothing?
Is it an initial setting, or can you change at will?

2017-12-03 15:12 UTC, Michiyamenotehifunana commented
You can change it at will, in real time.

2017-12-04 00:40 UTC, Kevak commented
Code all looks good but ya need to comment yer code. A big issue in a lotta codebases is code that isn't fully commented and explained. Please do so. Explain what each proc does in //comments

2017-12-04 00:45 UTC, Partheo commented
Doesn't actually modify/improve any current code, leave the "Code improvement" tag for that.

2017-12-04 01:24 UTC, Kevak commented
It adds the framework for recolorable stuff. So technically it is an improvement imo.

2017-12-04 01:31 UTC, Partheo requested changes
Please leave the code for the clothes in /haven/code/modules/clothing/under/polychromatic_clothes.dm, and the code for the wardrobe in /haven/code/game/objects/structures/crates_lockers/closets/wardrome.dm. I know it's a pain, but that's where the code should go were it not in the modular folder. If you want, I can do that myself.

Also, since you're overwriting a TG proc, please update haven/changes.md.

2017-12-04 01:31 UTC, Partheo commented on haven/code/polychromic_clothes.dm
> +
Stacked IF statements shouldn't have whitespace between them.

2017-12-04 01:31 UTC, Partheo commented on haven/code/polychromic_clothes.dm
> +	to_chat(user, "<span class='notice'>Alt-click to recolor it.</span>")
Muh immershuns

2017-12-04 01:31 UTC, Partheo commented on haven/code/polychromic_clothes.dm
> +//replaces the jumpsuit contents of the mixed wardrobe
How do you know that this overwrites the TG proc?

2017-12-04 02:56 UTC, Partheo requested changes

2017-12-04 02:56 UTC, Partheo commented on haven/code/polychromic_clothes.dm
> +	if(!in_range(src, user))
You should check if they're in range first.

2017-12-04 02:56 UTC, Partheo commented on haven/code/polychromic_clothes.dm
> +	if(user.incapacitated() || !istype(user) || !in_range(src, user))
This check is redundant, since you've already checked for these just before.

2017-12-04 12:56 UTC, Michiyamenotehifunana commented
_Should_ be done properly now.

2017-12-04 20:24 UTC, Partheo approved these changes

2017-12-04 20:24 UTC, Partheo commented
Looks good. I'll test this today unless Neri wants to.

2017-12-04 20:45 UTC, Kevak commented
Go ahead

2017-12-05 09:27 UTC, merged